language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

services: mysql

before_script:
  - mysql -e 'create database pmt;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install -n --dev --prefer-source
  - app/console doctrine:schema:create
  - mysql pmt < doc/test_data.sql
  - app/console fos:user:create username email@domain.com password

script: phpunit -c app
