services:
    pmt_web.type.issue_form:
        class: PMT\WebBundle\Form\Type\IssueFormType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: issue_form }
    pmt_web.twig.issue_extension:
        class: PMT\WebBundle\Twig\IssueExtension
        tags:
            - { name: twig.extension }
