services:
    pmt_core.issue_repository:
        class: PMT\CoreBundle\Entity\Issue\IssueRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PMT\\CoreBundle\\Entity\\Issue\\Issue"]

    pmt_core.project_repository:
        class: PMT\CoreBundle\Entity\Project\ProjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PMT\\CoreBundle\\Entity\\Project\\Project"]

    pmt_core.workflow_step_repository:
        class: PMT\CoreBundle\Entity\Workflow\WorkflowStepRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PMT\\CoreBundle\\Entity\\Workflow\\WorkflowStep"]

    kernel.listener.comment_listener:
        class: PMT\CoreBundle\EventListener\CommentListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: fos_comment.comment.post_persist, method: registerNewComment }

    pmt_core.log_repository:
        class: PMT\CoreBundle\Entity\Workflow\WorkflowStepRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PMT\\CoreBundle\\Entity\\Workflow\\WorkflowStep"]
        calls:
            - ["setLogger", ["@logger"]]
